In [12]:
#Multivariate Imputation by chianed equation

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
df=np.round(pd.read_csv(r"C:\Users\heman\Downloads\50_Startups.csv")[["R&D Spend","Administration","Marketing Spend","Profit"]]/10000)

In [8]:
df=df.sample(5)

In [9]:
df=df.iloc[:,:-1]
df

    R&D Spend  Administration
4        14.0             9.0
36        3.0            13.0
46        0.0            12.0
30        6.0            12.0
3        14.0            12.0

In [10]:
df.iloc[1,0]=np.nan
df.iloc[3,-1]=np.nan
df.iloc[-1,-1]=np.nan

In [11]:
df

    R&D Spend  Administration
4        14.0             9.0
36        NaN            13.0
46        0.0            12.0
30        6.0             NaN
3        14.0             NaN