In [1]:
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv(r"C:\Users\heman\Downloads\train.csv",usecols=["Survived","Age","Fare"])

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.impute import MissingIndicator

In [6]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=["Survived"],axis=1),df["Survived"],test_size=0.2,random_state=42)

In [7]:
x_train.isnull().sum()

Age     140
Fare      0
dtype: int64

In [9]:
x_test.isnull().sum()

Age     37
Fare     0
dtype: int64

In [10]:
SI=SimpleImputer()

In [12]:
x_train_trf=SI.fit_transform(x_train)
x_test_trf=SI.transform(x_test)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
LG=LogisticRegression()
LG.fit(x_train_trf,y_train)

LogisticRegression()

In [18]:
y_pred=LG.predict(x_test_trf)

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
print(accuracy_score(y_test,y_pred))

0.6480446927374302

In [21]:
# specifying Missing indicator

In [22]:
SIM=SimpleImputer(add_indicator=True)

In [24]:
x_train_SIM=SIM.fit_transform(x_train)
x_test_SIm=SIM.transform(x_test)

In [28]:
x_train_SIM

array([[ 45.5   ,  28.5   ,   0.    ],
       [ 23.    ,  13.    ,   0.    ],
       [ 32.    ,   7.925 ,   0.    ],
       ...,
       [ 41.    ,  14.1083,   0.    ],
       [ 14.    , 120.    ,   0.    ],
       [ 21.    ,  77.2875,   0.    ]])

In [29]:
x_test_SIm

array([[ 29.49884615,  15.2458    ,   1.        ],
       [ 31.        ,  10.5       ,   0.        ],
       [ 20.        ,   7.925     ,   0.        ],
       [  6.        ,  33.        ,   0.        ],
       [ 14.        ,  11.2417    ,   0.        ],
       [ 26.        ,  78.85      ,   0.        ],
       [ 29.49884615,   7.75      ,   1.        ],
       [ 16.        ,  18.        ,   0.        ],
       [ 16.        ,   7.75      ,   0.        ],
       [ 19.        ,  26.2833    ,   0.        ],
       [ 37.        ,  53.1       ,   0.        ],
       [ 44.        ,   8.05      ,   0.        ],
       [ 29.49884615,  25.4667    ,   1.        ],
       [ 30.        ,   7.225     ,   0.        ],
       [ 36.        ,  13.        ,   0.        ],
       [ 16.        ,  39.4       ,   0.        ],
       [ 42.        ,  52.5542    ,   0.        ],
       [ 29.49884615,   7.8292    ,   1.        ],
       [ 27.        ,  13.        ,   0.        ],
       [ 47.        ,  52.        ,   0.        ],
       [ 24.        ,   7.8958    ,   0.        ],
       [ 34.        ,  26.55      ,   0.        ],
       [ 19.        ,   7.8542    ,   0.        ],
       [ 20.        ,   9.225     ,   0.        ],
       [ 29.49884615,  14.5       ,   1.        ],
       [ 10.        ,  27.9       ,   0.        ],
       [ 40.        ,  27.7208    ,   0.        ],
       [ 31.        ,  13.        ,   0.        ],
       [  4.        ,  27.9       ,   0.        ],
       [ 31.        ,   7.8542    ,   0.        ],
       [ 19.        ,   7.8958    ,   0.        ],
       [ 22.        ,   7.75      ,   0.        ],
       [ 29.49884615,  30.6958    ,   1.        ],
       [ 29.49884615,   7.55      ,   1.        ],
       [ 18.        ,   8.05      ,   0.        ],
       [ 27.        ,  14.4542    ,   0.        ],
       [ 28.        ,  35.5       ,   0.        ],
       [ 29.49884615,   7.75      ,   1.        ],
       [ 30.        ,  31.        ,   0.        ],
       [ 29.49884615,   7.8958    ,   1.        ],
       [ 21.        ,  73.5       ,   0.        ],
       [ 29.        ,   7.0458    ,   0.        ],
       [ 29.49884615,   8.05      ,   1.        ],
       [ 29.49884615,   7.75      ,   1.        ],
       [ 45.        ,  14.4542    ,   0.        ],
       [ 16.        ,  34.375     ,   0.        ],
       [ 19.        ,   8.1583    ,   0.        ],
       [ 23.        ,   9.225     ,   0.        ],
       [ 24.        ,   7.05      ,   0.        ],
       [ 58.        , 113.275     ,   0.        ],
       [  5.        ,  19.2583    ,   0.        ],
       [ 52.        ,  93.5       ,   0.        ],
       [ 40.        ,  27.9       ,   0.        ],
       [ 11.        , 120.        ,   0.        ],
       [ 65.        ,   7.75      ,   0.        ],
       [ 18.        ,  79.65      ,   0.        ],
       [ 32.        ,  10.5       ,   0.        ],
       [ 50.        , 247.5208    ,   0.        ],
       [ 35.        ,  21.        ,   0.        ],
       [ 19.        ,   7.8792    ,   0.        ],
       [ 21.        ,   7.775     ,   0.        ],
       [ 13.        ,  19.5       ,   0.        ],
       [ 28.        ,  26.        ,   0.        ],
       [ 29.49884615,  25.925     ,   1.        ],
       [ 29.49884615,   7.75      ,   1.        ],
       [ 57.        ,  10.5       ,   0.        ],
       [ 21.        ,  73.5       ,   0.        ],
       [ 29.        ,   7.875     ,   0.        ],
       [ 17.        ,   7.2292    ,   0.        ],
       [ 52.        ,  78.2667    ,   0.        ],
       [ 26.        ,  26.        ,   0.        ],
       [ 18.        , 262.375     ,   0.        ],
       [ 26.        ,  30.        ,   0.        ],
       [ 39.        ,  83.1583    ,   0.        ],
       [ 23.        ,   7.8542    ,   0.        ],
       [ 36.        ,  15.55      ,   0.        ],
       [ 30.5       ,   7.75      ,   0.        ],
       [ 22.        ,  49.5       ,   0.        ],
       [ 38.        ,  13.        ,   0.        ],
       [ 41.        ,  20.2125    ,   0.        ],
       [ 16.        ,  39.6875    ,   0.        ],
       [ 29.        ,  10.5       ,   0.        ],
       [ 40.        , 134.5       ,   0.        ],
       [ 29.49884615,   7.7375    ,   1.        ],
       [ 56.        ,  30.6958    ,   0.        ],
       [ 71.        ,  49.5042    ,   0.        ],
       [ 31.        , 113.275     ,   0.        ],
       [ 30.        ,  56.9292    ,   0.        ],
       [ 38.        ,   0.        ,   0.        ],
       [ 29.49884615,   7.25      ,   1.        ],
       [  9.        ,  20.525     ,   0.        ],
       [  9.        ,  31.275     ,   0.        ],
       [ 61.        ,  32.3208    ,   0.        ],
       [ 29.49884615,   7.7292    ,   1.        ],
       [ 29.49884615,   7.8958    ,   1.        ],
       [ 28.        ,   7.8542    ,   0.        ],
       [ 48.        ,  52.        ,   0.        ],
       [ 45.        ,   8.05      ,   0.        ],
       [ 36.        ,  13.        ,   0.        ],
       [ 27.        ,   7.8958    ,   0.        ],
       [ 64.        ,  26.        ,   0.        ],
       [ 35.        ,   7.125     ,   0.        ],
       [ 19.        ,  91.0792    ,   0.        ],
       [ 38.        ,   7.05      ,   0.        ],
       [ 30.5       ,   8.05      ,   0.        ],
       [ 25.        ,   7.775     ,   0.        ],
       [ 40.        ,  39.        ,   0.        ],
       [ 47.        ,  38.5       ,   0.        ],
       [ 30.        ,   9.5       ,   0.        ],
       [ 40.        ,  31.        ,   0.        ],
       [ 29.49884615,  52.        ,   1.        ],
       [ 20.5       ,   7.25      ,   0.        ],
       [ 29.49884615,  89.1042    ,   1.        ],
       [ 36.        ,  26.2875    ,   0.        ],
       [ 29.49884615, 221.7792    ,   1.        ],
       [ 20.        ,   9.8458    ,   0.        ],
       [ 71.        ,  34.6542    ,   0.        ],
       [ 36.        ,  12.875     ,   0.        ],
       [ 22.        ,  29.        ,   0.        ],
       [ 48.        ,  34.375     ,   0.        ],
       [ 23.        ,  11.5       ,   0.        ],
       [ 32.        ,  76.2917    ,   0.        ],
       [ 63.        ,  77.9583    ,   0.        ],
       [  0.83      ,  29.        ,   0.        ],
       [ 25.        ,   7.25      ,   0.        ],
       [ 35.        ,  26.55      ,   0.        ],
       [ 49.        ,  25.9292    ,   0.        ],
       [ 24.        ,  79.2       ,   0.        ],
       [ 29.49884615,  14.4583    ,   1.        ],
       [ 21.        ,   8.05      ,   0.        ],
       [ 29.49884615,   7.8792    ,   1.        ],
       [ 29.49884615,  15.2458    ,   1.        ],
       [ 29.49884615,   0.        ,   1.        ],
       [  5.        ,  12.475     ,   0.        ],
       [ 49.        ,  56.9292    ,   0.        ],
       [ 15.        ,  14.4542    ,   0.        ],
       [ 29.49884615, 110.8833    ,   1.        ],
       [ 29.        ,   7.775     ,   0.        ],
       [ 42.        ,   7.55      ,   0.        ],
       [ 18.        ,  17.8       ,   0.        ],
       [ 21.        ,   8.4333    ,   0.        ],
       [ 44.        ,  26.        ,   0.        ],
       [ 28.        ,  13.        ,   0.        ],
       [ 37.        ,  26.        ,   0.        ],
       [ 39.        ,  29.125     ,   0.        ],
       [ 34.        ,  32.5       ,   0.        ],
       [ 30.        ,  13.        ,   0.        ],
       [ 66.        ,  10.5       ,   0.        ],
       [ 29.49884615, 146.5208    ,   1.        ],
       [ 43.        ,   8.05      ,   0.        ],
       [ 29.49884615,   8.7125    ,   1.        ],
       [ 24.        ,   7.4958    ,   0.        ],
       [ 18.        ,   7.7958    ,   0.        ],
       [ 29.49884615,  24.15      ,   1.        ],
       [ 29.49884615,   8.05      ,   1.        ],
       [ 29.49884615,   7.05      ,   1.        ],
       [ 29.49884615,  56.4958    ,   1.        ],
       [ 29.49884615,   7.7875    ,   1.        ],
       [ 36.        ,  26.        ,   0.        ],
       [ 32.        ,  15.5       ,   0.        ],
       [ 23.5       ,   7.2292    ,   0.        ],
       [ 29.49884615,  26.55      ,   1.        ],
       [ 39.        ,  13.        ,   0.        ],
       [ 29.49884615,  82.1708    ,   1.        ],
       [ 29.49884615,   8.4583    ,   1.        ],
       [ 65.        ,  61.9792    ,   0.        ],
       [ 23.        ,  10.5       ,   0.        ],
       [ 29.49884615,  51.8625    ,   1.        ],
       [ 22.        ,   7.8958    ,   0.        ],
       [ 35.        ,   7.05      ,   0.        ],
       [ 23.        ,  63.3583    ,   0.        ],
       [ 18.        ,  13.        ,   0.        ],
       [ 36.        ,  26.3875    ,   0.        ],
       [  9.        ,  15.2458    ,   0.        ],
       [ 17.        ,   7.125     ,   0.        ],
       [ 29.49884615,   7.225     ,   1.        ],
       [ 38.        ,  31.3875    ,   0.        ],
       [ 17.        ,  10.5       ,   0.        ],
       [  4.        ,  16.7       ,   0.        ]])

In [30]:
LGS=LogisticRegression()

In [31]:
LGS.fit(x_train_SIM,y_train)

LogisticRegression()

In [32]:
Y_pred_sim=LGS.predict(x_test_SIm)

In [33]:
print(accuracy_score(y_test,Y_pred_sim))

0.6368715083798883

In [34]:
mi=MissingIndicator()

In [35]:
mi.fit(x_train)

MissingIndicator()

In [36]:
x_train_mi=mi.transform(x_train)

In [37]:
x_test_mi=mi.transform(x_test)

In [38]:
x_train_mi

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False]])

In [39]:
x_test_mi

array([[ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False]])

In [40]:
x_train["missing_indicator"]=x_train_mi
x_test["missing_indicator"]=x_test_mi

In [44]:
x_train.sample(5)

      Age     Fare  missing_indicator
297   2.0  151.550              False
741  36.0   78.850              False
366  60.0   75.250              False
728  25.0   26.000              False
719  33.0    7.775              False

In [45]:
x_test.sample(5)

      Age     Fare  missing_indicator
837   NaN   8.0500               True
292  36.0  12.8750              False
670  40.0  39.0000              False
493  71.0  49.5042              False
854  44.0  26.0000              False