In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv(r"C:\Users\heman\Downloads\train.csv")

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df=df.dropna()

In [5]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [6]:
df=df[["Age",'Pclass',"SibSp","Parch","Survived"]]

In [7]:
df

      Age  Pclass  SibSp  Parch  Survived
1    38.0       1      1      0         1
3    35.0       1      1      0         1
6    54.0       1      0      0         0
10    4.0       3      1      1         1
11   58.0       1      0      0         1
..    ...     ...    ...    ...       ...
871  47.0       1      1      1         1
872  33.0       1      0      0         0
879  56.0       1      0      1         1
887  19.0       1      0      0         1
889  26.0       1      0      0         1

[183 rows x 5 columns]

In [8]:
x=df.iloc[:,:4]
y=df["Survived"]

In [9]:
x

      Age  Pclass  SibSp  Parch
1    38.0       1      1      0
3    35.0       1      1      0
6    54.0       1      0      0
10    4.0       3      1      1
11   58.0       1      0      0
..    ...     ...    ...    ...
871  47.0       1      1      1
872  33.0       1      0      0
879  56.0       1      0      1
887  19.0       1      0      0
889  26.0       1      0      0

[183 rows x 4 columns]

In [10]:
y

1      1
3      1
6      0
10     1
11     1
      ..
871    1
872    0
879    1
887    1
889    1
Name: Survived, Length: 183, dtype: int64

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
from sklearn.model_selection import cross_val_score

In [13]:
print(np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20)))

0.6988888888888889

In [14]:
#feature construction

In [15]:
df["family_size"]=df["SibSp"]+df["Parch"]+1

In [16]:
df

      Age  Pclass  SibSp  Parch  Survived  family_size
1    38.0       1      1      0         1            2
3    35.0       1      1      0         1            2
6    54.0       1      0      0         0            1
10    4.0       3      1      1         1            3
11   58.0       1      0      0         1            1
..    ...     ...    ...    ...       ...          ...
871  47.0       1      1      1         1            3
872  33.0       1      0      0         0            1
879  56.0       1      0      1         1            2
887  19.0       1      0      0         1            1
889  26.0       1      0      0         1            1

[183 rows x 6 columns]

In [17]:
def Ftype(num):
    if num==0:
        return 0
    elif num>1 and num<4:
        return 1
    else:
        return 2

In [18]:
df["Family_type"]=df["family_size"].apply(Ftype)

In [19]:
df.drop(columns=["SibSp","Parch","family_size"],axis=1,inplace=True)

In [20]:
df

      Age  Pclass  Survived  Family_type
1    38.0       1         1            1
3    35.0       1         1            1
6    54.0       1         0            2
10    4.0       3         1            1
11   58.0       1         1            2
..    ...     ...       ...          ...
871  47.0       1         1            1
872  33.0       1         0            2
879  56.0       1         1            1
887  19.0       1         1            2
889  26.0       1         1            2

[183 rows x 4 columns]

In [21]:
print(np.mean(cross_val_score(LogisticRegression(),df[["Age","Pclass","Family_type"]],df["Survived"],scoring="accuracy",cv=20)))

0.7100000000000001

In [22]:
# feature splliting

In [66]:
df=pd.read_csv(r"C:\Users\heman\Downloads\train.csv")

In [67]:
df=df[["Age",'Pclass',"SibSp","Parch","Survived","Name"]]

In [68]:
df["Title"]=df["Name"].str.split(",",expand=True)[1].str.split(".",expand=True)[0]

In [69]:
df

,Age,Pclass,SibSp,Parch,Survived,Name,Title
0,22.0,3,1,0,0,"Braund, Mr. Owen Harris",Mr
1,38.0,1,1,0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Mrs
2,26.0,3,0,0,1,"Heikkinen, Miss. Laina",Miss
3,35.0,1,1,0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Mrs
4,35.0,3,0,0,0,"Allen, Mr. William Henry",Mr
...,...,...,...,...,...,...,...
886,27.0,2,0,0,0,"Montvila, Rev. Juozas",Rev
887,19.0,1,0,0,1,"Graham, Miss. Margaret Edith",Miss
888,NaN,3,1,2,0,"Johnston, Miss. Catherine Helen ""Carrie""",Miss
889,26.0,1,0,0,1,"Behr, Mr. Karl Howell",Mr
890,32.0,3,0,0,0,"Dooley, Mr. Patrick",Mr

In [70]:
df.drop(columns=["Name"],axis=1,inplace=True)

In [71]:
df.groupby("Title").mean()["Survived"]

Title
Capt            0.000000
Col             0.500000
Don             0.000000
Dr              0.428571
Jonkheer        0.000000
Lady            1.000000
Major           0.500000
Master          0.575000
Miss            0.697802
Mlle            1.000000
Mme             1.000000
Mr              0.156673
Mrs             0.792000
Ms              1.000000
Rev             0.000000
Sir             1.000000
the Countess    1.000000
Name: Survived, dtype: float64

In [75]:
df["is_married"]=0

In [72]:
df['Is_Married'] = 0
df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1

C:\Users\heman\AppData\Local\Temp\ipykernel_14496\2254989826.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1
C:\Users\heman\AppData\Local\Temp\ipykernel_14496\2254989826.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1

In [56]:
def married(value):
    if value=="Mrs":
        return 1
    else:
        return 0

In [57]:
df["Is_Married"]=df["Title"].apply(married)

In [59]:
df.drop(columns=["is_married"],axis=1,inplace=True)

In [73]:
df

      Age  Pclass  SibSp  Parch  Survived  Title  Is_Married
0    22.0       3      1      0         0     Mr           0
1    38.0       1      1      0         1    Mrs           0
2    26.0       3      0      0         1   Miss           0
3    35.0       1      1      0         1    Mrs           0
4    35.0       3      0      0         0     Mr           0
..    ...     ...    ...    ...       ...    ...         ...
886  27.0       2      0      0         0    Rev           0
887  19.0       1      0      0         1   Miss           0
888   NaN       3      1      2         0   Miss           0
889  26.0       1      0      0         1     Mr           0
890  32.0       3      0      0         0     Mr           0

[891 rows x 7 columns]

In [74]:
df["Is_Married"].unique()

array([0], dtype=int64)