In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
Messages=pd.read_csv(r"C:\Users\heman\Downloads\messages.csv")
orders=pd.read_csv(r"C:\Users\heman\Downloads\orders.csv")

In [3]:
Messages

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [4]:
orders

           date  product_id  city_id  orders
0    2019-12-10        5628       25       3
1    2018-08-15        3646       14     157
2    2018-10-23        1859       25       1
3    2019-08-17        7292       25       1
4    2019-01-06        4344       25       3
..          ...         ...      ...     ...
995  2018-10-08         255       13       1
996  2018-12-06        5521        7       1
997  2019-05-07         487       26      14
998  2019-03-03        1503       21       2
999  2019-10-15        6371        7      22

[1000 rows x 4 columns]

In [5]:
orders["date"]=pd.to_datetime(orders["date"])

In [6]:
 orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [7]:
orders

          date  product_id  city_id  orders
0   2019-12-10        5628       25       3
1   2018-08-15        3646       14     157
2   2018-10-23        1859       25       1
3   2019-08-17        7292       25       1
4   2019-01-06        4344       25       3
..         ...         ...      ...     ...
995 2018-10-08         255       13       1
996 2018-12-06        5521        7       1
997 2019-05-07         487       26      14
998 2019-03-03        1503       21       2
999 2019-10-15        6371        7      22

[1000 rows x 4 columns]

In [8]:
orders["year"]=orders["date"].dt.year

In [9]:
orders["day"]=orders["date"].dt.date

In [10]:
orders["month"]=orders["date"].dt.month

In [11]:
orders=orders.drop(columns=["day"],axis=1)

In [12]:
orders

          date  product_id  city_id  orders  year  month
0   2019-12-10        5628       25       3  2019     12
1   2018-08-15        3646       14     157  2018      8
2   2018-10-23        1859       25       1  2018     10
3   2019-08-17        7292       25       1  2019      8
4   2019-01-06        4344       25       3  2019      1
..         ...         ...      ...     ...   ...    ...
995 2018-10-08         255       13       1  2018     10
996 2018-12-06        5521        7       1  2018     12
997 2019-05-07         487       26      14  2019      5
998 2019-03-03        1503       21       2  2019      3
999 2019-10-15        6371        7      22  2019     10

[1000 rows x 6 columns]

In [13]:
orders["day"]=orders["date"].dt.day

In [14]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
 4   year        1000 non-null   int32
 5   month       1000 non-null   int32
 6   day         1000 non-null   int32
dtypes: datetime64[ns](1), int32(3), int64(3)
memory usage: 43.1 KB

In [15]:
# orders=orders.drop(columns=["date"],axis=1)

In [16]:
# orders["date"]=orders["year"].astype(str)+"/"+orders["month"].astype(str)+"/"+orders["day"].astype(str)

In [15]:
orders

          date  product_id  city_id  orders  year  month  day
0   2019-12-10        5628       25       3  2019     12   10
1   2018-08-15        3646       14     157  2018      8   15
2   2018-10-23        1859       25       1  2018     10   23
3   2019-08-17        7292       25       1  2019      8   17
4   2019-01-06        4344       25       3  2019      1    6
..         ...         ...      ...     ...   ...    ...  ...
995 2018-10-08         255       13       1  2018     10    8
996 2018-12-06        5521        7       1  2018     12    6
997 2019-05-07         487       26      14  2019      5    7
998 2019-03-03        1503       21       2  2019      3    3
999 2019-10-15        6371        7      22  2019     10   15

[1000 rows x 7 columns]

In [16]:
Messages

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [17]:
import datetime
today=datetime.datetime.today()
today

datetime.datetime(2025, 7, 19, 16, 35, 22, 197236)

In [18]:
today - orders["date"]

0     2048 days 16:35:22.197236
1     2530 days 16:35:22.197236
2     2461 days 16:35:22.197236
3     2163 days 16:35:22.197236
4     2386 days 16:35:22.197236
                 ...
995   2476 days 16:35:22.197236
996   2417 days 16:35:22.197236
997   2265 days 16:35:22.197236
998   2330 days 16:35:22.197236
999   2104 days 16:35:22.197236
Name: date, Length: 1000, dtype: timedelta64[ns]

In [19]:
(today - orders["date"]).dt.days

0      2048
1      2530
2      2461
3      2163
4      2386
       ...
995    2476
996    2417
997    2265
998    2330
999    2104
Name: date, Length: 1000, dtype: int64

In [20]:
orders["months_ago"] = ((today.year - orders["date"].dt.year) * 12 +(today.month - orders["date"].dt.month)).astype(int)

In [21]:
orders

          date  product_id  city_id  orders  year  month  day  months_ago
0   2019-12-10        5628       25       3  2019     12   10          67
1   2018-08-15        3646       14     157  2018      8   15          83
2   2018-10-23        1859       25       1  2018     10   23          81
3   2019-08-17        7292       25       1  2019      8   17          71
4   2019-01-06        4344       25       3  2019      1    6          78
..         ...         ...      ...     ...   ...    ...  ...         ...
995 2018-10-08         255       13       1  2018     10    8          81
996 2018-12-06        5521        7       1  2018     12    6          79
997 2019-05-07         487       26      14  2019      5    7          74
998 2019-03-03        1503       21       2  2019      3    3          76
999 2019-10-15        6371        7      22  2019     10   15          69

[1000 rows x 8 columns]

In [22]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
 4   year        1000 non-null   int32
 5   month       1000 non-null   int32
 6   day         1000 non-null   int32
 7   months_ago  1000 non-null   int32
dtypes: datetime64[ns](1), int32(4), int64(3)
memory usage: 47.0 KB

In [23]:
Messages["date"]=pd.to_datetime(Messages["date"])

In [24]:
Messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [25]:
Messages

                   date                                                msg
0   2013-12-15 00:50:00                           ищу на сегодня мужика 37
1   2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2   2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3   2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4   2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                  ...                                                ...
995 2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996 2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997 2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998 2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999 2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [26]:
Messages["time"]=Messages["date"].dt.time

In [27]:
Messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
 2   time    1000 non-null   object
dtypes: datetime64[ns](1), object(2)
memory usage: 23.6+ KB

In [28]:
Messages

,date,msg,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23:11:00
...,...,...,...
995,2012-03-16 00:50:00,ПАРЕНЬ СДЕЛАЕТ МАССАЖ ЖЕНЩИНАМ -066-877-32-44,00:50:00
996,2014-01-23 23:14:00,сельский п 23 ищу девушку для отношений,23:14:00
997,2012-10-15 23:37:00,Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...,23:37:00
998,2012-06-21 23:34:00,7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14,23:34:00
999,2014-06-19 23:25:00,Парень поласкает девушке... т.0662035584,23:25:00

In [32]:
Messages["time"]=Messages["time"].astype(str)

In [39]:
# Messages["hours"]=Messages["time"].str.split(":").str[0]

In [36]:
Messages[["hour", "min", "sec"]] = Messages["time"].str.split(":", expand=True)

In [40]:
Messages

,date,msg,time,hour,min,sec,hours
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,00:50:00,00,50,00,00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23:40:00,23,40,00,23
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,00:21:00,00,21,00,00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,00:31:00,00,31,00,00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23:11:00,23,11,00,23
...,...,...,...,...,...,...,...
995,2012-03-16 00:50:00,ПАРЕНЬ СДЕЛАЕТ МАССАЖ ЖЕНЩИНАМ -066-877-32-44,00:50:00,00,50,00,00
996,2014-01-23 23:14:00,сельский п 23 ищу девушку для отношений,23:14:00,23,14,00,23
997,2012-10-15 23:37:00,Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...,23:37:00,23,37,00,23
998,2012-06-21 23:34:00,7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14,23:34:00,23,34,00,23
999,2014-06-19 23:25:00,Парень поласкает девушке... т.0662035584,23:25:00,23,25,00,23

In [42]:
Messages.drop(columns=["hours"],axis=1,inplace=True)

In [43]:
Messages['hours'] = Messages['date'].dt.hour
Messages['mins'] = Messages['date'].dt.minute
Messages['secs'] = Messages['date'].dt.second

In [44]:
Messages

,date,msg,time,hour,min,sec,hours,mins,secs
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,00:50:00,00,50,00,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23:40:00,23,40,00,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,00:21:00,00,21,00,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,00:31:00,00,31,00,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23:11:00,23,11,00,23,11,0
...,...,...,...,...,...,...,...,...,...
995,2012-03-16 00:50:00,ПАРЕНЬ СДЕЛАЕТ МАССАЖ ЖЕНЩИНАМ -066-877-32-44,00:50:00,00,50,00,0,50,0
996,2014-01-23 23:14:00,сельский п 23 ищу девушку для отношений,23:14:00,23,14,00,23,14,0
997,2012-10-15 23:37:00,Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...,23:37:00,23,37,00,23,37,0
998,2012-06-21 23:34:00,7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14,23:34:00,23,34,00,23,34,0
999,2014-06-19 23:25:00,Парень поласкает девушке... т.0662035584,23:25:00,23,25,00,23,25,0